In [18]:
import pandas as pd
#base e dados da base
texto = pd.read_csv("base1.csv", names=["loc", "v(g)", "ev(g)",\
                                      "iv(g)", "n", "v", "l", "d","i", "e", "b", "t", "lOCode",\
                                      "loComment", "lOBlank", "locCodeAndComment", "uniq_Op", "uniq_Opnd", \
                                      "total_Op", "total_Opnd", "branchCount", "defects"])
texto.describe()

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,b,t,lOCode,loComment,lOBlank,locCodeAndComment
count,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,1.088500e+04,10885.000000,1.088500e+04,10885.000000,10885.000000,10885.00000,10885.000000
mean,42.016178,6.348590,3.401047,4.001599,114.389738,673.758017,0.135335,14.177237,29.439544,3.683637e+04,0.224766,2.046465e+03,26.252274,2.737529,4.62554,0.370785
std,76.593332,13.019695,6.771869,9.116889,249.502091,1938.856196,0.160538,18.709900,34.418313,4.343678e+05,0.646408,2.413154e+04,59.611201,9.008608,9.96813,1.907969
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,11.000000,2.000000,1.000000,1.000000,14.000000,48.430000,0.030000,3.000000,11.860000,1.619400e+02,0.020000,9.000000e+00,4.000000,0.000000,0.00000,0.000000
50%,23.000000,3.000000,1.000000,2.000000,49.000000,217.130000,0.080000,9.090000,21.930000,2.031020e+03,0.070000,1.128300e+02,13.000000,0.000000,2.00000,0.000000
75%,46.000000,7.000000,3.000000,4.000000,119.000000,621.480000,0.160000,18.900000,36.780000,1.141643e+04,0.210000,6.342500e+02,28.000000,2.000000,5.00000,0.000000
max,3442.000000,470.000000,165.000000,402.000000,8441.000000,80843.080000,1.300000,418.200000,569.780000,3.107978e+07,26.950000,1.726655e+06,2824.000000,344.000000,447.00000,108.000000

Criando função de treinamento

In [117]:
import numpy as np
import math
from collections import Counter
class Bean_object:
    def __init__(self, feature, label):
        self.feature = feature
        self.label = label
        self.classified = -1

class Knn:
    #eucllidian_distancy = pd.add(l1,l2)
    a = lambda self, x: x**2
    def __init__(self, distancy_func = 0):
        self.items = {}
        self.distancy_func = distancy_func
        
    def train(self, data):
        for i in data:
            self.items[i.feature] = i.label
        
    
    def teste(self, data, dist_func, k = 1):
        for item in data:
            item.classified = self.teste_val(item, k, dist_func)
        return data
    
    def find_nearst(self, item, k, dist_func):
        nearst = sorted([(x, dist_func(item, x)) for x in self.items], key = lambda tup: tup[1])
        return nearst[:k]
    
    def teste_val(self, item, k, dist_func):
        nearsts = self.find_nearst(item, k, dist_func)
        class_list = map(lambda x: self.items[x[0]] ,nearsts)
        return Counter(class_list).most_common(1)[0][0]

    def accuracy(self, data):
        pass
    
    def precision(self, data):
        pass
    
    def recall(self, data):
        pass
def main():
    c = Knn()
    data = []
    data.append(Bean_object((10, 15), True))
    data.append(Bean_object((5, 6), True))
    data.append(Bean_object((3, 5), False))
    data.append(Bean_object((0, 1), False))
    f = lambda x, y: 0
    c.train(data)
    
    #teste 
    data_teste = []
    data_teste.append(Bean_object((10, 11), False))
    data_teste.append(Bean_object((1, 11), False))
    data_teste.append(Bean_object((9, 11), False))
    result = c.teste(data_teste, f)
    for i in result:
        print(i.classified)
    
    
        
main()

True
True
True